-- Convert students.id from int/serial to bigint (safe on empty DB)
ALTER TABLE students
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE students
    ALTER COLUMN id TYPE BIGINT;

-- recreate identity sequence behavior (Postgres 10+)
ALTER TABLE students
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
