-- Convert users.id from int/serial to bigint identity
ALTER TABLE users
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE users
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE users
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
